# Segmentation sapience
segmentaion:
  service_url: http://127.0.0.1:7860
  pre_preservation_classes:
    - Left_Hand
    - Right_Hand
  force_preservation_classes:
    - Hair
  soft_preservation_classes:
    - Apparel
    - Left_Hand
    - Left_Lower_Arm
    - Left_Upper_Arm
    - Right_Hand
    - Right_Lower_Arm
    - Right_Upper_Arm
  clothing_classes:
    - Upper_Clothing
    - Lower_Clothing

persone_attributes:
  device: "cuda:0"
  model_name: "openai/clip-vit-base-patch32"
  attributes:
    gender:
      texts:
        - "a photo of a man"
        - "a photo of a woman"
      labels:
        - "man"
        - "woman"
    age:
      texts:
        - "a photo of a baby"
        - "a photo of a child"
        - "a photo of a teenager"
        - "a photo of an adult"
        - "a photo of a middle-aged person"
        - "a photo of a senior person"
        - "a photo of an elderly person"
      labels:
        - "baby"
        - "child"
        - "teenager"
        - "adult"
        - "middle-aged"
        - "senior"
        - "elderly"



# Device settings
device: cuda

# Paths
base_path: yisol/IDM-VTON
example_path: ./example

